import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const headers={"content-type":"application/json","cache-control":"no-store","x-content-type-options":"nosniff"};
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("");}
function secureEqual(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
function cleanSymbol(v:unknown){return String(v||"").trim().toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,30);}
Deno.serve(async(req:Request)=>{if(req.method!=="POST")return new Response(JSON.stringify({error:"method_not_allowed"}),{status:405,headers});try{
 const b=await req.json(); const action=String(b?.action||"list").toLowerCase(); const sb=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}}); const projection="id,exchange,symbol,target_order_id,target_order_link_id,rationale,confidence,status,expires_at,result,created_at,updated_at,executed_at,processing_started_at,processing_owner,replacement_side,replacement_order_type,replacement_quote_amount_usdc,replacement_base_quantity,replacement_limit_price,replacement_rationale,replacement_confidence";
 const expected=String(Deno.env.get("SUPABASE_MCP_TOKEN")||"");const supplied=String(req.headers.get("x-chk-token")||"");const serverOk=!!expected&&secureEqual(expected,supplied);
 if(action==="server_create_cancel"){
  if(!serverOk)return new Response(JSON.stringify({error:"unauthorized"}),{status:401,headers}); const fp=String(b?.accountFingerprint||"").trim(); const symbol=cleanSymbol(b?.symbol); const target=String(b?.targetOrderId||"").trim().slice(0,128); const link=String(b?.targetOrderLinkId||"").trim().slice(0,128)||null; const rationale=String(b?.rationale||"").trim().slice(0,4000); const conf=b?.confidence==null?null:Math.max(0,Math.min(99,Math.round(Number(b.confidence))));
  if(!/^[a-f0-9]{32,128}$/i.test(fp)||!symbol.endsWith("USDC")||!target)return new Response(JSON.stringify({error:"invalid_cancel"}),{status:400,headers}); const expiresMs=Math.max(5*60*1000,Math.min(24*60*60*1000,Number(b?.expiresInMinutes||120)*60*1000));
  const row:any={account_fingerprint:fp,exchange:"BYBIT",symbol,target_order_id:target,target_order_link_id:link,rationale,confidence:conf,status:"pending",expires_at:new Date(Date.now()+expiresMs).toISOString(),replacement_side:b?.replacementSide?String(b.replacementSide).toUpperCase():null,replacement_order_type:b?.replacementOrderType?String(b.replacementOrderType).toUpperCase():null,replacement_quote_amount_usdc:b?.replacementQuoteAmountUsdc==null?null:Number(b.replacementQuoteAmountUsdc),replacement_base_quantity:b?.replacementBaseQuantity==null?null:Number(b.replacementBaseQuantity),replacement_limit_price:b?.replacementLimitPrice==null?null:Number(b.replacementLimitPrice),replacement_rationale:b?.replacementRationale?String(b.replacementRationale).slice(0,4000):null,replacement_confidence:b?.replacementConfidence==null?null:Math.max(0,Math.min(99,Math.round(Number(b.replacementConfidence))))};
  if(row.replacement_quote_amount_usdc!=null&&(!(row.replacement_quote_amount_usdc>0)||row.replacement_quote_amount_usdc>30.0000001))return new Response(JSON.stringify({error:"invalid_replacement_amount"}),{status:400,headers});
  const {data:existing,error:ee}=await sb.from("chk_cancel_proposals").select(projection).eq("account_fingerprint",fp).eq("status","pending").eq("target_order_id",target).maybeSingle();if(ee)throw ee;if(existing)return new Response(JSON.stringify({ok:true,duplicate:true,proposal:existing}),{status:200,headers});
  const {data,error}=await sb.from("chk_cancel_proposals").insert(row).select(projection).single();if(error)throw error;return new Response(JSON.stringify({ok:true,duplicate:false,proposal:data}),{status:200,headers});
 }
 if(action==="server_list_cancel"){if(!serverOk)return new Response(JSON.stringify({error:"unauthorized"}),{status:401,headers});const fp=String(b?.accountFingerprint||"").trim();if(!/^[a-f0-9]{32,128}$/i.test(fp))return new Response(JSON.stringify({error:"invalid_account_fingerprint"}),{status:400,headers});const {data,error}=await sb.from("chk_cancel_proposals").select(projection).eq("account_fingerprint",fp).order("created_at",{ascending:false}).limit(Math.max(1,Math.min(100,Number(b?.limit||40))));if(error)throw error;return new Response(JSON.stringify({ok:true,proposals:data||[]}),{status:200,headers});}
 const deviceId=String(b?.deviceId||"").trim();const deviceSecret=String(b?.deviceSecret||"");if(!/^[a-f0-9-]{32,80}$/i.test(deviceId)||deviceSecret.length<32||deviceSecret.length>256)return new Response(JSON.stringify({error:"invalid_device_credentials"}),{status:400,headers});
 const {data:device,error:de}=await sb.from("chk_crypto_snapshots").select("device_secret_hash,account_fingerprint").eq("device_id",deviceId).eq("exchange","BYBIT").maybeSingle();if(de)throw de;if(!device||device.device_secret_hash!==await sha256(deviceSecret))return new Response(JSON.stringify({error:"device_auth_failed"}),{status:401,headers});const fp=String(device.account_fingerprint||"");if(!fp)return new Response(JSON.stringify({error:"bybit_not_synced"}),{status:409,headers});const now=new Date().toISOString();await sb.from("chk_cancel_proposals").update({status:"expired",updated_at:now}).eq("account_fingerprint",fp).eq("status","pending").lt("expires_at",now);
 if(action==="list"){const {data:pending,error:e1}=await sb.from("chk_cancel_proposals").select(projection).eq("account_fingerprint",fp).eq("status","pending").order("created_at",{ascending:false}).limit(20);if(e1)throw e1;const {data:recent,error:e2}=await sb.from("chk_cancel_proposals").select(projection).eq("account_fingerprint",fp).neq("status","pending").order("updated_at",{ascending:false}).limit(20);if(e2)throw e2;return new Response(JSON.stringify({ok:true,pending:pending||[],recent:recent||[]}),{status:200,headers});}
 if(action==="claim"){const id=String(b?.id||"");const at=new Date().toISOString();const {data,error}=await sb.from("chk_cancel_proposals").update({status:"processing",processing_started_at:at,processing_owner:deviceId,updated_at:at}).eq("id",id).eq("account_fingerprint",fp).eq("status","pending").gt("expires_at",at).select(projection).maybeSingle();if(error)throw error;if(!data)return new Response(JSON.stringify({error:"proposal_not_claimable"}),{status:409,headers});return new Response(JSON.stringify({ok:true,proposal:data}),{status:200,headers});}
 if(action==="mark_result"){const id=String(b?.id||"");const status=String(b?.status||"").toLowerCase();if(!["executed","error","rejected"].includes(status))return new Response(JSON.stringify({error:"invalid_update"}),{status:400,headers});const expectedStatus=status==="rejected"?"pending":"processing";const {data:before,error:be}=await sb.from("chk_cancel_proposals").select(projection+",account_fingerprint").eq("id",id).eq("account_fingerprint",fp).eq("status",expectedStatus).maybeSingle();if(be)throw be;if(!before)return new Response(JSON.stringify({error:"proposal_state_conflict"}),{status:409,headers});const result=b?.result&&typeof b.result==="object"&&!Array.isArray(b.result)?b.result:{};const update:any={status,result,updated_at:new Date().toISOString()};if(status==="executed")update.executed_at=new Date().toISOString();let q=sb.from("chk_cancel_proposals").update(update).eq("id",id).eq("account_fingerprint",fp).eq("status",expectedStatus);if(expectedStatus==="processing")q=q.eq("processing_owner",deviceId);const {data,error}=await q.select("id,status,result,updated_at,executed_at").maybeSingle();if(error)throw error;if(!data)return new Response(JSON.stringify({error:"proposal_state_conflict"}),{status:409,headers});let replacementProposal=null;if(status==="executed"&&before.replacement_side&&before.replacement_order_type&&before.replacement_quote_amount_usdc){const source=`cancel-replacement:${id}`;const {data:existing,error:ee}=await sb.from("chk_trade_proposals").select("id,status").eq("account_fingerprint",fp).eq("source",source).maybeSingle();if(ee)throw ee;if(existing)replacementProposal=existing;else{const replacement:any={account_fingerprint:fp,exchange:"BYBIT",symbol:before.symbol,side:before.replacement_side,order_type:before.replacement_order_type,quote_amount_usdc:before.replacement_quote_amount_usdc,base_quantity:before.replacement_base_quantity,limit_price:before.replacement_limit_price,rationale:String(before.replacement_rationale||`Remplacement après annulation ${before.target_order_id}`),confidence:before.replacement_confidence,source,status:"pending",expires_at:new Date(Date.now()+2*60*60*1000).toISOString()};const {data:created,error:ce}=await sb.from("chk_trade_proposals").insert(replacement).select("id,status,symbol,side,order_type,quote_amount_usdc,base_quantity,limit_price,expires_at").single();if(ce)throw ce;replacementProposal=created;}}return new Response(JSON.stringify({ok:true,proposal:data,replacementProposal}),{status:200,headers});}
 return new Response(JSON.stringify({error:"unknown_action"}),{status:400,headers});
}catch(e){console.error("chk-cancel-proposals",e);return new Response(JSON.stringify({error:"cancel_proposals_failed",message:String(e?.message||e).slice(0,180)}),{status:500,headers});}});
